apiVersion: v1
data:
  filebeat.yml: |-
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /root/app-log/*/*.log
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
kind: ConfigMap
metadata:
  creationTimestamp: "2020-01-21T09:13:03Z"
  labels:
    k8s-app: filebeat
  name: filebeat-config
  namespace: wso2
  resourceVersion: "13846609"
  selfLink: /api/v1/namespaces/wso2/configmaps/filebeat-config
  uid: 3aa9190c-3c2e-11ea-9539-62e868a82fc8
